
/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Entry__1 = IDL.Record({
  'principal' : IDL.Principal,
  'comment' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const Preferences = IDL.Record({
  'preferredStyles' : IDL.Vec(IDL.Text),
  'colorPalettes' : IDL.Vec(IDL.Text),
  'gender' : IDL.Text,
  'bodyType' : IDL.Text,
  'budgetRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'occasions' : IDL.Vec(IDL.Text),
});
export const Profile = IDL.Record({
  'principal' : IDL.Principal,
  'preferences' : Preferences,
});
export const Garment = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Recommendation = IDL.Record({
  'trendTags' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'occasionTags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'garments' : IDL.Vec(Garment),
  'stylingRationale' : IDL.Text,
  'imageUrl' : IDL.Text,
  'styleCategory' : IDL.Text,
});
export const Entry = IDL.Record({
  'popularityScore' : IDL.Nat,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'season' : IDL.Text,
  'category' : IDL.Text,
});
export const Data = IDL.Record({
  'preferredStyles' : IDL.Vec(IDL.Text),
  'colorPalettes' : IDL.Vec(IDL.Text),
  'gender' : IDL.Text,
  'bodyType' : IDL.Text,
  'budgetRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
  'occasions' : IDL.Vec(IDL.Text),
});
export const Result = IDL.Record({
  'principal' : IDL.Principal,
  'preferredStyles' : IDL.Vec(IDL.Text),
  'completed' : IDL.Bool,
  'quizAnswers' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'getAllRatings' : IDL.Func([IDL.Text], [IDL.Vec(Entry__1)], ['query']),
  'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getProfile' : IDL.Func([], [Profile], []),
  'getRecommendations' : IDL.Func([], [IDL.Vec(Recommendation)], ['query']),
  'getSavedOutfits' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getTrendsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
  'hasCompletedQuiz' : IDL.Func([], [IDL.Bool], ['query']),
  'rateOutfit' : IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
  'removeOutfit' : IDL.Func([IDL.Text], [], []),
  'saveOutfit' : IDL.Func([IDL.Text], [], []),
  'savePreferences' : IDL.Func([Data], [], []),
  'saveQuizResult' : IDL.Func([Result], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Entry__1 = IDL.Record({
    'principal' : IDL.Principal,
    'comment' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const Preferences = IDL.Record({
    'preferredStyles' : IDL.Vec(IDL.Text),
    'colorPalettes' : IDL.Vec(IDL.Text),
    'gender' : IDL.Text,
    'bodyType' : IDL.Text,
    'budgetRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'occasions' : IDL.Vec(IDL.Text),
  });
  const Profile = IDL.Record({
    'principal' : IDL.Principal,
    'preferences' : Preferences,
  });
  const Garment = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Recommendation = IDL.Record({
    'trendTags' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'occasionTags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'garments' : IDL.Vec(Garment),
    'stylingRationale' : IDL.Text,
    'imageUrl' : IDL.Text,
    'styleCategory' : IDL.Text,
  });
  const Entry = IDL.Record({
    'popularityScore' : IDL.Nat,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'season' : IDL.Text,
    'category' : IDL.Text,
  });
  const Data = IDL.Record({
    'preferredStyles' : IDL.Vec(IDL.Text),
    'colorPalettes' : IDL.Vec(IDL.Text),
    'gender' : IDL.Text,
    'bodyType' : IDL.Text,
    'budgetRange' : IDL.Record({ 'max' : IDL.Nat, 'min' : IDL.Nat }),
    'occasions' : IDL.Vec(IDL.Text),
  });
  const Result = IDL.Record({
    'principal' : IDL.Principal,
    'preferredStyles' : IDL.Vec(IDL.Text),
    'completed' : IDL.Bool,
    'quizAnswers' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'getAllRatings' : IDL.Func([IDL.Text], [IDL.Vec(Entry__1)], ['query']),
    'getAverageRating' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'getProfile' : IDL.Func([], [Profile], []),
    'getRecommendations' : IDL.Func([], [IDL.Vec(Recommendation)], ['query']),
    'getSavedOutfits' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getTrendsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
    'hasCompletedQuiz' : IDL.Func([], [IDL.Bool], ['query']),
    'rateOutfit' : IDL.Func([IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)], [], []),
    'removeOutfit' : IDL.Func([IDL.Text], [], []),
    'saveOutfit' : IDL.Func([IDL.Text], [], []),
    'savePreferences' : IDL.Func([Data], [], []),
    'saveQuizResult' : IDL.Func([Result], [], []),
  });
};

export const init = ({ IDL }) => { return []; };